### PR TITLE
fix(webserver): do not unnecessarily restart webserver

### LINKED ISSUE #114: Apache2 should not restart unnecessarily after a deploy
The current implementation of the Apache2 webserver driver always restarts at the end of a deployment. This restart can be necessary when the Apache2 configuration has changed so much that modules must be loaded or reloaded, for example, but it is not generally necessary as a deploy typically will only result in the underlying app(s) having been updated without change to the apache configuration.

As an opsworks_ruby user, I would like the default behavior for deploys to be to `reload` the apache2/httpd service rather than `restart`-ing it, so that the server will continue to serve requests throughout the deployment Chef run.

Implementation expectations:
- Any action (e.g. installing a module) that would cause the Apache2 configuration to become invalid and require a restart, will still cause Apache2 to restart at the end of the Chef run
- Otherwise, Apache2 will only reload after a deploy

Bonus points:
- Implement the same for nginx

### PR DESCRIPTION
**Pull request by nickmarden**
Fixes #114

### CODE REVIEW

File: libraries/drivers_dsl_notifies.rb [hunk 1]
```diff
@@ -31,6 +31,18 @@ def notifies
...
+        r = context.send(what, name, &block)
+        r.notifies(action, "service[#{service_name}]", timing)
+        r
+      end
+
+      %i[execute file link package template].each do |what|
+        define_method "notifying_#{what}" do |name, action = :restart, timing = :delayed, &block|
+          notifying_resource(what, name, action, timing, &block)
+        end
+      end
```
Comment (ajgon) [inline libraries/drivers_dsl_notifies.rb]:
```ruby
alias notifying_execute notifying_resource
alias notifying_file notifying_resource
alias notifying_link notifying_resource
alias notifying_package notifying_resource
alias notifying_template notifying_resource
```
won't work here? This construction is really hard to read, and you won't see the intention.
Instead of what, you can then use `__callee__` to get the method name (or `__callee__.sub('notifying_', '')`).

Comment (nickmarden) [reply libraries/drivers_dsl_notifies.rb]: I also find it hard to discern the intention in the `__callee__` construct, but your concern is valid so for complete readability please see my amended version [here](https://github.com/ajgon/opsworks_ruby/pull/115/commits/d74a56ce1ac7321e25b4fd8aa69a120115932564).
